psycopg/psycopg

docs/lib/libpq_docs.py
tox.ini

This adds a tox environment to build the docs.
Also included one change to make the docs build with python 3.7.

add a tox environment to build the docs

---

.gitignore
docs/news.rst
psycopg/psycopg/cursor.py
psycopg/psycopg/server_cursor.py
tests/test_cursor.py
tests/test_cursor_async.py
tests/test_server_cursor.py
tests/test_server_cursor_async.py

fixes #125 
@dvarrazzo not sure if this is the right way to fix. If this is not, your kind advice required. Thanks.

fix: check if cursor is closed

---

psycopg/psycopg/__init__.py
psycopg_c/psycopg_c/__init__.py
psycopg_pool/psycopg_pool/__init__.py
tests/conftest.py
tests/fix_mypy.py
tests/pool/test_pool.py
tests/test_module.py
tests/test_typing.py

@dlax I have made the mypy fixture usable from the entire test suite, also used here for an example. Do you think it might be useful somewhere else?

Version checks

---

pyproject.toml
tests/types/test_array.py
tests/types/test_composite.py
tests/types/test_datetime.py
tests/types/test_hstore.py
tests/types/test_multirange.py
tests/types/test_range.py
tests/types/test_shapely.py

First step towards having the test suite type-checked.

Let mypy check tests/types files

---

psycopg_pool/psycopg_pool/pool_async.py

Hi!
Our CI in typeshed identified a future error in your code: https://github.com/python/typeshed/pull/6783
So, I am doing a pro-active PR to fix that 🙂 
Local test that it works (with the future stubs):

Change type of `wait` in `pool_async.py`

---

docs/api/cursors.rst
docs/news.rst
psycopg/psycopg/cursor.py
psycopg/psycopg/cursor_async.py
psycopg/psycopg/server_cursor.py
tests/test_cursor.py
tests/test_cursor_async.py

returning `executemany()`

---

docs/advanced/async.rst

following #246 to avoid further useless questions :)

doc: give more context to disconnection detection recipe

---

docs/news.rst
psycopg/psycopg/copy.py
psycopg/psycopg/generators.py
tests/test_copy.py
tests/test_copy_async.py

Fix infinite loop in copy and worker thread swallowing exceptions

---

psycopg/psycopg/_pipeline.py
psycopg/psycopg/connection.py
psycopg/psycopg/connection_async.py
psycopg/psycopg/cursor.py
psycopg/psycopg/cursor_async.py
tests/test_pipeline.py
tests/test_pipeline_async.py

Based on #260 to resolve the `rowcount` issue in particular.

follow-up executemany() & pipeline

---

psycopg/psycopg/_pipeline.py
psycopg/psycopg/cursor.py
tests/test_pipeline.py
tests/test_pipeline_async.py

(see commit messages for details; part of this would make sense with #271 as well)

pipeline: various improvements on sync, flush and fetch steps 

---

docs/advanced/index.rst
docs/advanced/pipeline.rst
docs/api/connections.rst
docs/api/cursors.rst
docs/api/errors.rst
docs/api/objects.rst
docs/news.rst
psycopg/psycopg/_pipeline.py
psycopg/psycopg/connection.py

@dlax happy to have your feedback about these docs. Thank you!

Pipeline mode docs

---

docs/news.rst
psycopg/psycopg/pq/pq_ctypes.py
tests/test_concurrency.py

The connection is passed via the optional *arg.
Fixes #300

Use a static notification function for PQsetNoticeReceiver. Fixes #300

---

tests/fix_db.py

By using STDERR, we get the trace directly in pytest output for failing tests. Though this requires care when used in combination with --capture=sys because this would make sys.stderr an in-memory file.
When STDERR is used, we don't insert the header since the test case identifier will be interleaved already.

test: allow to trace libpq to STDERR, rename option to --pq-trace

---

docs/basic/install.rst

Fixing typo in docs/install.rst

#397: Fix typo in install.rst

---

psycopg/psycopg/cursor.py
psycopg/psycopg/cursor_async.py

Namely, also lock the connection when closing the generator, in the finally clause, where we are fetching results.
It seems safer/needed. Or am I missing something?

fix: lock the connection during all stream() lifetime

---

psycopg/psycopg/_compat.py
psycopg/psycopg/version.py
psycopg/setup.cfg
psycopg/setup.py
psycopg_c/psycopg_c/_compat.py
psycopg_c/psycopg_c/version.py
psycopg_c/setup.cfg
psycopg_c/setup.py
psycopg_pool/psycopg_pool/_compat.py
psycopg_pool/psycopg_pool/version.py
psycopg_pool/setup.cfg
psycopg_pool/setup.py
tools/bump_version.py

@dvarrazzo  Here is my preliminary PR for #465. Please kindly review this draft and let me know if I am on the right path. I would like to continue to submit changes for psycopg_c and psycopg_pool and backporting after your feedback.

Refactor get version from metadata (#465)

---

psycopg/psycopg/_typeinfo.py

A little refactoring of what just done by @CaselIT, touching on a couple of topic emerged during review. This MR includes two different things, in the two commits, but I hope it's simple enough to review.
Another more complex refactoring is on the way, whose aim is to break the import loop that requires this, and other modules, to use lazy imports, and I'd like to make that MR more self-contained as @dlax has pointed out :)
This MR:
- removes the use of the Union[Connection, AsyncConnection] type, which was only used internally,
- removes the assumption that Postgres > 10 and CRDB will only have ranges after it already acquired `to_regtype()`: use the `cls._to_regtype()` uniformly.
@CaselIT, @dlax What do you think?

Refactor typeinfo 1

---

docs/api/cursors.rst

This functionality in Materialize has been renamed.

[docs] Materialize `TAIL` -> `SUBSCRIBE`

---

.github/workflows/3rd-party-tests.yml

Django integration pipeline.

---

docs/news.rst
psycopg/psycopg/_pipeline.py
psycopg/psycopg/_preparing.py
tests/test_pipeline.py
tests/test_pipeline_async.py

fixes #585 (plus a couple of docstring updates)

fix: always validate PrepareManager cache in pipeline mode

---

docs/api/rows.rst
docs/news.rst
psycopg/psycopg/rows.py
tests/test_rows.py

added `scalar_row` factory

---

docs/api/connections.rst
docs/news.rst
psycopg/psycopg/_compat.py
psycopg/psycopg/_connection_base.py
psycopg/psycopg/_copy.py
psycopg/psycopg/_copy_async.py
psycopg/psycopg/_copy_base.py
psycopg/psycopg/connection.py
psycopg/psycopg/connection_async.py
psycopg/psycopg/cursor.py
psycopg/psycopg/cursor_async.py
psycopg/psycopg/generators.py
psycopg_c/psycopg_c/_psycopg.pyi
psycopg_c/psycopg_c/_psycopg/generators.pyx
tests/test_concurrency_async.py
tests/test_connection.py
tests/test_connection_async.py
tests/test_generators.py
tests/test_tpc.py
tests/test_tpc_async.py

~~based on #754 (first commit); implements the proposal from https://github.com/psycopg/psycopg/issues/534#issuecomment-2034747801~~
fix #534

encrypted and non-blocking cancellation

---

.github/workflows/tests.yml
docs/news.rst
psycopg_c/psycopg_c/_psycopg/copy.pyx
psycopg_c/psycopg_c/types/array.pyx
psycopg_c/psycopg_c/types/datetime.pyx
psycopg_c/psycopg_c/types/numeric.pyx

Solve undefined behaviour caused by unaligned access

---

docs/advanced/cursors.rst

Add instructions for pgbouncer simple query protocol

---

docs/advanced/cursors.rst
docs/api/cursors.rst
docs/news.rst
psycopg/psycopg/__init__.py
psycopg/psycopg/raw_cursor.py
tests/_test_cursor.py
tests/test_cursor_server.py
tests/test_cursor_server_async.py
tools/async_to_sync.py

I had this changeset in a branch and forgot to make a MR of it

Add RawServerCursor class

---

.github/workflows/tests.yml
psycopg_c/psycopg_c/pq/pgconn.pyx
psycopg_c/psycopg_c/types/array.pyx
psycopg_c/psycopg_c/types/datetime.pyx
psycopg_c/psycopg_c/types/numeric.pyx

Drop a few warnings compiling the C extension.
Close #867

Fix warnings

---

psycopg_c/psycopg_c/types/datetime.pyx

Avoid violating strict aliasing rule in interval binary loader

---

.github/workflows/packages-bin.yml
.github/workflows/tests.yml
docs/basic/install.rst
docs/news.rst
docs/release.rst
psycopg/setup.cfg
psycopg_c/setup.cfg
psycopg_pool/setup.cfg
tools/build/build_macos_arm64.sh

Related:
- Closes https://github.com/psycopg/psycopg/issues/889

Build Python 3.13 wheels

---

docs/news_pool.rst
psycopg_pool/psycopg_pool/pool.py
psycopg_pool/psycopg_pool/pool_async.py
tests/pool/test_pool.py
tests/pool/test_pool_async.py

addresses https://github.com/psycopg/psycopg/issues/1014

fix: connection reset after test

---

docs/news.rst
psycopg/psycopg/_conninfo_attempts.py
psycopg/psycopg/_conninfo_attempts_async.py
tests/test_connection.py
tests/test_connection_async.py
tests/test_conninfo_attempts.py
tests/test_conninfo_attempts_async.py

First attempt all the servers in standby mode, then fall back to any mode.
Fix #1021.
CC. @AndrewJackson2020

fix: implement libpq semantic for target_session_attrs=prefer-standby

---

docs/news.rst
psycopg/psycopg/types/hstore.py
tests/types/test_hstore.py

Closes https://github.com/psycopg/psycopg/issues/1030

Support binary protocol for hstore

---

docs/news.rst
psycopg/psycopg/connection.py
psycopg/psycopg/connection_async.py
psycopg/psycopg/pq/pq_ctypes.py
psycopg_c/psycopg_c/pq/pgconn.pyx
tests/test_concurrency.py

See for example #1055 where this behaviour is reported, #1076 where it is further discussed.

Stop processing connection attempts after pressing Ctrl-C

---

docs/basic/usage.rst
docs/news.rst
psycopg/psycopg/connection.py
psycopg/psycopg/connection_async.py

After the struggle in figuring out slowness on connection (#888, #1055), improving and documenting connection logging.
See the docs change for an example of the logging produced. It should help to figure out the connection attemtps and where any stops.

Better logging

---

.github/workflows/packages-bin.yml
.github/workflows/tests.yml
docs/advanced/async.rst
docs/basic/install.rst
docs/news.rst
psycopg/psycopg/_compat.py
psycopg/psycopg/connection_async.py
psycopg/pyproject.toml
psycopg_c/pyproject.toml
psycopg_pool/pyproject.toml
tests/conftest.py
tests/fix_proxy.py
tests/pool/test_pool_async_noasyncio.py
tests/pproxy_fix.py
tests/scripts/bench-411.py
tests/test_concurrency_async.py
tests/test_psycopg_dbapi20.py
tests/utils.py
tools/ci/build_libpq.sh

Work in progress, until the release gets to a more stable state.

Add support for Python 3.14
