psycopg/psycopg

psycopg3/psycopg3/connection.py
Rollback exception is no longer available on the Transaction object.
=> Remove obsolete references to Transaction.Rollback

psycopg3/psycopg3/pq/__init__.py, psycopg3/psycopg3/pq/_pq_ctypes.py, tests/fix_pq.py
Open to suggestions on:
1. How to 'detect' Windows: There are a number of options: `os.name`, `sys.platform`, `os.uname()`, and I have no strong opinion on which is best to use.
2. How to de-duplicate this code (if deemed necessary, since there are only two occurrences, one of which is in test code): I looked around for places where to put a helper method (and fixed a typo in `pq.__init__` while I was at it) but wasn't sure where it would best fit.
=> Adapt find_library() call to find libpq.dll on Windows

tests/test_concurrency.py, tests/test_connection.py
* Skip test_connect_timeout() on Windows for the time being as
Connection.connect() hangs for some reason. This skip can probably
go away once connection timeouts are implemented.
* test_multiprocess_close(): Turn LocalPath instance back into a str
before putting it back into env["PYTHONPATH"] to avoid failure in:
_winapi.CreateProcess(): TypeError: environment can only contain str
=> Windows compatibility for tests

psycopg3/psycopg3/types/__init__.py, tests/test_copy.py
This is useful to silent mypy errors when implicit reexport is disabled
(e.g. in strict mode) like:
error: Module 'psycopg3.types' does not explicitly export attribute
'Jsonb'; implicit reexport disabled  [attr-defined]
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport
Accordingly, we import Int4 from psycopg3.types directly in
test_copy.py.
=> Re-export names from psycopg3.types

.github/workflows/lint.yml
This is useful to prevent regressions during pull requests as the docs build uses `-W` flag of sphinx.
=> Check documentation build in CI

psycopg3/setup.py
I was trying to run with python 3.10, so needed pytest 6.2.4. (There another issue after that.)
It seems that nothing breaks with more recent versions of all of these.
=> Upgrade testing libraries

docs/basic/install.rst
See [the wiki](https://en.wikipedia.org/wiki/MacOS). The naming timeline so far: Mac OS X → OS X → macOS.
=> Change macOS name in installation documentation

.gitignore, psycopg/psycopg/connection_async.py, tests/conftest.py, tests/test_connection_async.py
Make test work under windows, by requiring a compatible event loop.
Also raise an exception when trying to use an async connection with an incompatible event loop on windows.
I'm not sure about what the most appropriate exception is in this case, InterfaceError?
- TODO: test of the error
Fixes #76
=> Improve async story in the test on windows

tests/pq/test_pgconn.py
Quoting https://www.postgresql.org/docs/14/libpq-status.html:
>  [PQtty] no longer does anything, but it remains for backwards
>  compatibility. The function always return an empty string.
Or perhaps we should drop 'tty' property (and binding), since this is at
least obsolete since PostgreSQL 7.4?
=> Adjust test on PGconn.tty for libpq 14

psycopg_c/psycopg_c/pq/libpq.pxd
Follow-up 515e246b5f933ba93fdde93a03287c6940dbf85b; these values were
only added for the Python definition of the enum.
Related to #74.
=> Add missing ExecStatusType enum values for pipeline mode

.mypy.ini
When running mypy on the tests/ directory, the top-level mypy
configuration is used and strict mode is thus enforced whereas tests
code is not typed. As mypy might be run in people editors by default,
the current situation makes this uncomfortable.
By disabling obvious checks, we get a nicer developer experience. A more
straightforward option would be to set 'check_untyped_defs = False', but
this would prevent valid code to be checked, so the current proposal is
a trade-off.
=> Explicitly disallow some mypy checks for tests/ (to improve developer experience)

.github/workflows/packages.yml, tools/build/wheel_linux_before_all.sh
The v2.2.x version of cibuildwheel adds supports for building `musllinux`[^1] wheels. Meaning Alpine users can finally take advantage of binary installations.
[^1]: https://www.python.org/dev/peps/pep-0656/
=> Update cibuildwheel to v2.2.2 to build `musllinux` wheels

.github/workflows/tests.yml, pyproject.toml
This reduces duplication and makes the configuration available when
testing outside CI.
=> Configure pytest warning control in pyproject.toml

psycopg/psycopg/waiting.py, tests/test_waiting.py
Replaces #107 and would be needed for the pipeline mode #93.
=> support RW ready in waiting functions

.gitignore, psycopg/setup.py, pyproject.toml
This does not check psycopg_c code, and I'm sure if/how this can be achieved, but this is enough to be useful to me for now.
=> Add a minimal coverage configuration

psycopg/psycopg/rows.py, psycopg/setup.py
One 'type: ignore' is no longer needed, it seems.
=> Use mypy 0.920

docs/advanced/adapt.rst, docs/advanced/async.rst, docs/advanced/cursors.rst, docs/advanced/pool.rst, docs/advanced/prepare.rst, docs/api/connections.rst, docs/api/module.rst, docs/basic/adapt.rst, docs/basic/copy.rst, docs/basic/from_pg2.rst, docs/basic/install.rst, docs/basic/params.rst, docs/basic/pgtypes.rst, docs/basic/transactions.rst, docs/basic/usage.rst, psycopg/psycopg/connection.py
This pull request fixes typos and grammar in the documentation and docstrings.
Note that I may have missed a few typos. Also I'm not a native english speaker, but this should be an improvement nonetheless.
This version of the pull request incorporates changes requested in #185
=> Fix typos and grammar in documentation.

docs/api/abc.rst
https://pypi.org/project/codespell/
=> abc.rst: Fix typos discovered by codespell

docs/basic/params.rst
In the named parameters example query, the name of the parameters are Python built in data types: `int` and `str`.
I think this is confusing because it looks like we are casting values passed as arguments instead of passing named arguments.
This MR replaces `int`, `str` and `date` arguments by keys `id`, `last_name` and `created_at` to remove the possible confusion.
=> fix: confusing named parameters in example query

docs/api/errors.rst, docs/api/pq.rst, psycopg/psycopg/pq/pq_ctypes.py
This improves the documentation of Error class, which refers to those
in the new pgconn attribute documentation.
(The base branch is `pgconn-in-exception`.)
* * *
The rest of `pgconn-in-exception` branch looks good to me and would certainly help with #242 (the OP is  a colleague of mine).
=> docs: document PGconn needs_password and used_password attributes

docs/news.rst, psycopg/psycopg/_pipeline.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py, psycopg/psycopg/errors.py, tests/fix_pq.py, tests/test_cursor.py, tests/test_cursor_async.py, tests/test_pipeline.py, tests/test_pipeline_async.py
Optimization of `Cursor.executemany()` using pipelines (#145). 
This branch is based on @dlax pipeline4 branch (#175) and will be merged after the other MR is.
Speedup looks in the region of the 2.5x improvement.
```python
import psycopg
cnn = psycopg.connect("host=localhost", autocommit=True)
cur = cnn.cursor()
cur.execute("""
create temp table testmany (
id serial primary key, n1 int, n2 int, s1 text, s2 text)
""")
cur.executemany(
"insert into testmany (n1, n2, s1, s2) values (%s, %s, %s, %s)",
[(20, 5000, "foobar", "foobar" * 100)] * 100000,
)
```
```
$ time python test-execmany.py 
real	0m8.586s
user	0m3.416s
sys	0m1.469s
$ git co -
Switched to branch 'executemany-pipeline'
$ time python test-execmany.py 
real	0m3.347s
user	0m2.432s
sys	0m0.903s
```
=> Executemany pipeline

docs/api/objects.rst, docs/api/pq.rst, psycopg/psycopg/conninfo.py, tests/test_conninfo.py
@dlax It occurred to me that we don't have a public way to check for the pipeline status. There is `Connection.pgconn.pipeline_status` but it sort of require "internal libpq knowledge". Ok with this?
Will flesh more docs (even just a "see also: pipeline mode") to the docs branch.
=> Add ConnectionInfo.pipeline_status

psycopg/psycopg/_cmodule.py
I'm fixing a bug in mypy's `--no-implicit-reexport` logic in
https://github.com/python/mypy/pull/12704 and mypy-primer flagged this
=> Re-export from psycopg._cmodule

docs/advanced/pipeline.rst
While reading the section, it is otherwise not obvious to understand
where to get the Pipeline object from.
=> docs: mention that conn.pipeline() yields a Pipeline object

psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/test_pipeline.py, tests/test_pipeline_async.py
When entering a transaction on a connection in pipeline mode, we open an
inner pipeline to ensure that a Sync is emitted at the end of
transaction thus restoring the connection in its expected state (i.e.
the same as in non-pipeline mode).
=> fix: wrap transaction in pipelines if the connection has one

docs/advanced/pipeline.rst, psycopg/psycopg/_pipeline.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, psycopg/psycopg/transaction.py, tests/test_connection.py, tests/test_connection_async.py, tests/test_pipeline.py, tests/test_pipeline_async.py
As highlighted in #296, we should make sure that on `sync()` and on `commit()` the state of the Python connection reflects what's in the server, in particular we should throw an exception if there is any error.
This MR fixes the behaviour of these functions as well as the nested transaction.
The tests also highlight a difference between pipeline and non-pipeline mode: if commit fails in pipeline mode, the transaction is left INERROR instead of going IDLE.
=> Sync the client on sync() and commit()

psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/conftest.py, tests/fix_db.py, tests/test_connection.py, tests/test_connection_async.py, tests/test_pipeline.py, tests/test_pipeline_async.py, tests/test_transaction.py, tests/test_transaction_async.py
Follow-up #297, almost resurrecting #271 (but without `nullcontext()`):
* Now running (almost) all transaction tests with and without the connection in pipeline mode;
* Fixing connection state at exit of transaction state;
* See the TODO in tests, about `Connection._check_intrans()`.
=> fix: wrap transaction in an outer pipeline if the connection has one

docs/advanced/cursors.rst, docs/api/cursors.rst, docs/basic/copy.rst, docs/basic/from_pg2.rst, docs/news.rst, psycopg/psycopg/__init__.py, psycopg/psycopg/_queries.py, psycopg/psycopg/client_cursor.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py, tests/test_client_cursor.py, tests/test_client_cursor_async.py, tests/test_copy.py, tests/test_copy_async.py, tests/test_cursor.py, tests/test_cursor_async.py, tests/test_server_cursor.py, tests/test_server_cursor_async.py, tests/utils.py
The heavy lifting for this changeset is actually done in #264. That changeset adds cast to literal values (e.g. casting `date(2000, 1, 1)` to `'2000-01-01'::date` rather than `'2000-01-01'`.
Once that building block is in place, a client-side cursor is little more than a cursor which uses a different `PostgresQuery`, which puts together the query with the values adapted to literals.
As a bonus of having introduced `PostgresClientQuery`, we can now very simply add parameters to `copy()`.
Plenty of tests, documentation, and also added `cursor.mogrify()` which I'm sure a lot of people may want to use, although there are better ways to do the same.
Close #101
=> Add client-side cursor

psycopg/psycopg/connection.py, tests/test_tpc.py, tests/test_tpc_async.py
This is to get the NotSupported raised directly when calling
tpc_prepare() as expected in test_tpc_disabled().
(Other TPC tests pass when enabling pipeline mode overall.)
=> fix: sync pipeline after tpc_prepare()

docs/advanced/pipeline.rst, psycopg/psycopg/_pipeline.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/test_pipeline.py, tests/test_pipeline_async.py, tests/test_transaction.py
When entering a nested pipeline and the outer one has pending commands,
we now sync the pipeline. This is probably less surprising at it makes
the implicit transaction from a nested pipeline isolated from the outer
one.
Fix https://github.com/psycopg/psycopg/issues/309.
---
second commit cherry-picked from 9ca0991f892d6ede9e6f5cd6327f9149170ac56a
=> fix: sync nested pipeline with pending commands upon enter

tests/typing_example.py
Follow up 2f6e7669f0b32e7a99dd6db0ef41a18af119909f.
=> test: drop unneeded Cursor Row type variable from typing tests

.github/workflows/tests.yml, psycopg/psycopg/_pipeline.py, psycopg/psycopg/copy.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py, psycopg/psycopg/types/enum.py, tools/update_errors.py, tox.ini
codespell is blindingly fast so it is better not to restrict its vision.
```
./psycopg/psycopg/cursor.py:788: shoud ==> should
./psycopg/psycopg/copy.py:67: wee ==> we
./psycopg/psycopg/_pipeline.py:72: suports ==> supports
./psycopg/psycopg/_pipeline.py:151: matchs ==> matches
./psycopg/psycopg/_pipeline.py:221: insance ==> instance, insane
./psycopg/psycopg/cursor_async.py:148: shoud ==> should
./psycopg/psycopg/types/enum.py:42: memeber ==> member
./tools/update_errors.py:56: publically ==> publicly
./.github/workflows/tests.yml:44: minumum ==> minimum
```
=> codespell the entire repo?

docs/news.rst, psycopg/psycopg/_pipeline.py, tests/test_pipeline.py, tests/test_pipeline_async.py
Upon enter, transaction() checks the in-transaction status to determine if a BEGIN (when IDLE) or a SAVEPOINT (otherwise) should be inserted. However, in pipeline mode, if the pipeline is in "implicit transaction" (i.e. it has no active BEGIN) and statements have been sent, the in-transaction status might be ACTIVE if those statements have not yet completed (typically, when results have not been fetched).
By issuing a sync() before entering a nested pipeline (which will happen when entering transaction(), if already within a pipeline), we force completion of those statements, and thus get a predictable in-transaction status before entering the transaction() block.
Closes #374.
=> fix: also sync nested pipeline when a transaction is active

docs/basic/install.rst
Saw this warning, and I think it's outdated now, after #162, so I thought I'd just remove it.
=> Remove warning about missing binary package for M1

docs/news.rst, psycopg/psycopg/connection.py, tests/test_pipeline.py, tests/test_pipeline_async.py
Prior to this change, the following code:
with conn.pipeline():
conn.execute("select 'x'").fetchone()
conn.execute("select 'y'")
would produce the following libpq trace:
F	13	Parse	 "" "BEGIN" 0
F	14	Bind	 "" "" 0 0 1 0
F	6	Describe	 P ""
F	9	Execute	 "" 0
F	18	Parse	 "" "select 'x'" 0
F	14	Bind	 "" "" 0 0 1 0
F	6	Describe	 P ""
F	9	Execute	 "" 0
F	4	Flush
B	4	ParseComplete
B	4	BindComplete
B	4	NoData
B	10	CommandComplete	 "BEGIN"
B	4	ParseComplete
B	4	BindComplete
B	33	RowDescription	 1 "?column?" NNNN 0 NNNN 65535 -1 0
B	11	DataRow	 1 1 'x'
B	13	CommandComplete	 "SELECT 1"
F	13	Parse	 "" "BEGIN" 0
F	14	Bind	 "" "" 0 0 1 0
F	6	Describe	 P ""
F	9	Execute	 "" 0
F	18	Parse	 "" "select 'y'" 0
F	14	Bind	 "" "" 0 0 1 0
F	6	Describe	 P ""
F	9	Execute	 "" 0
B	4	ParseComplete
B	4	BindComplete
B	4 …
=> fix: sync pipeline after implicit BEGIN

psycopg/psycopg/_pipeline.py, psycopg/psycopg/version.py, psycopg_c/psycopg_c/version.py
We remove repeated code in `__(a)exit__()` method of `(Async)Pipeline` by passing the exception value to `_exit()` method of `BasePipeline`.
=> refactor: handle exit exception in BasePipeline._exit()

docs/news.rst, psycopg/psycopg/_typeinfo.py, tests/fix_crdb.py, tests/test_typeinfo.py
Fixes #473
I haven't modified the test, but it seems that the case of not existing type was already tested. Let me know if you thing additional tests are needed
=> Use to_regtype instead of ::regtype in type info queries

docs/news.rst, psycopg/psycopg/_typeinfo.py, tests/test_client_cursor.py, tests/test_client_cursor_async.py
TypeInfo had a hardcoded binary=True which doesn't work to well for ClientCursor.
Without this change we'd get:
```
Traceback (most recent call last):
File "/home/florian/sources/django.git/test.py", line 5, in <module>
print(TypeInfo.fetch(conn, "geometry"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/florian/.local/share/virtualenvs/django/lib/python3.11/site-packages/psycopg/_typeinfo.py", line 93, in fetch
cur.execute(cls._get_info_query(conn), {"name": name})
File "/home/florian/.local/share/virtualenvs/django/lib/python3.11/site-packages/psycopg/cursor.py", line 728, in execute
raise ex.with_traceback(None)
psycopg.NotSupportedError: client-side cursors don't support binary results
```
=> Fixed TypeInfo for ClientCursor.

README.rst
The previous [link](https://pip.pypa.io/en/stable/reference/pip_install/#install-editable) to pip.pypa was broken. This PR changes to the newer page on editable installs.
=> Fix broken link to pip docs

.github/workflows/3rd-party-tests.yml
Fixes: #488
NOTE: this is currently broken when using the file from pypi because of https://github.com/sqlalchemy/sqlalchemy/issues/9106
Since this pipeline does not run on PR, you can use https://github.com/CaselIT/psycopg/actions/workflows/3rd-party-tests.yml to see it running
=> Add sqlalchemy to the pipeline

tests/pool/test_pool_async_noasyncio.py
In commit b6cc8343159fc0a27365e09a3beef06433f3f1b5, we drop the global asyncio.set_event_loop_policy() for Windows in conftest.py, replacing it with asyncio_options to be used by the anyio test runner. However, test cases in test_pool_async_noasyncio.py are not "async def" so they would not use that anyio runner (nor did they use pytest-asyncio's runner before); but they need the event loop policy for Windows still. Accordingly, we configure the loop from "anyio_backend_options" in asyncio_run() fixture.
Hopefully fixing problems described in https://github.com/psycopg/psycopg/pull/352#issuecomment-1417965803.
=> test: use Windows asyncio policy in "non-asyncio" pool tests

psycopg/psycopg/pq/__init__.py, psycopg/psycopg/types/numeric.py, psycopg/setup.cfg, tests/constraints.txt, tests/test_copy.py, tests/test_copy_async.py, tests/test_server_cursor.py, tests/test_server_cursor_async.py
Some "type: ignore" no longer needed, some need a different kind.
=> chore: upgrade to mypy 1.0.0

docs/api/pool.rst, docs/news_pool.rst, psycopg_pool/psycopg_pool/base.py, psycopg_pool/psycopg_pool/null_pool.py, psycopg_pool/psycopg_pool/null_pool_async.py, psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py, tests/pool/test_pool_async.py
- define reconnect_failed callback in each pool implementation
- allow async functions as callbacks in async pools
- add a test
=> allow async reconnect_failed callback functions for async pool

tests/test_sql.py
Creating a base type, as done in that test, requires being a superuser.
It's annoying to me while running the test suite as the user I'm using on some machines is not a super-user.
=> tests: skip test_sql::test_invalid_name if not a super-user

docs/news.rst, psycopg/psycopg/types/composite.py, tests/types/test_composite.py
We need different dumpers because, in case a composite contains another composite, we need to call `dump_sequence()` on different sequences, so we row dumpers must be distinct.
Close #547
=> fix: don't reuse the same Transformer in composite dumper

docs/news.rst, psycopg/psycopg/types/json.py, tests/types/test_json.py
Work in progress to define what to do.
Close #541
=> fix(json): allow to register json dumpers on dict or other objects

docs/news.rst, psycopg/psycopg/types/json.py, tests/types/test_json.py
Some JSON libraries, in particular the widespread [orjson](https://github.com/ijl/orjson#quickstart) library, directly dump data in binary format.
This change allows it and avoids having to decode/encode in these cases by testing the return type of the `dumps` function.
=> Allow binary JSON dumps

tests/test_concurrency.py, tests/test_concurrency_async.py
ref https://github.com/NixOS/nixpkgs/pull/236281
```
psycopg> =================================== FAILURES =================================== psycopg> _____________________________ test_ctrl_c_handler ______________________________
psycopg>         t0 = time.time()
psycopg>         proc = sp.Popen([sys.executable, "-s", "-c", script], creationflags=creationflags)
psycopg>         proc.communicate()
psycopg>         t = time.time() - t0
psycopg>         assert proc.returncode == 0
psycopg> >       assert 1 < t < 2
psycopg> E       assert 3.7456982135772705 < 2
psycopg>
psycopg> tests/test_concurrency.py:293: AssertionError
```
=> Mark test_ctrl_c_handler as timing sensitive

psycopg/psycopg/rows.py, psycopg/setup.cfg, tests/constraints.txt, tests/test_pipeline.py, tests/test_pipeline_async.py
The issue previously mentioned about '# type: ignore[arg-type]' in rows.py got resolved.
The new '# type: ignore[comparison-overlap]' in test_pipeline*.py are due to https://github.com/python/mypy/issues/15509, a known regression from Mypy 1.4. We use the workaround documented in the release blog post https://mypy-lang.blogspot.com/2023/06/mypy-140-released.html (section "Narrowing Enum Values Using “==”").
=> chore: bump mypy to 1.4.1

docs/advanced/async.rst
Now that #543 is fixed, users shouldn't need to manually set up signal handlers to cancel operations any more.  Update the documentation to reflect this.
This fixes #599
=> Update documentation related to async and Ctrl-C

docs/news.rst, psycopg/psycopg/copy.py, tests/test_copy.py, tests/test_copy_async.py
We trigger the server to raise the QueryCanceled; however, the original exception has more information (the traceback). We can consider the server exception just a notification that cancellation worked as expected.
This is a mild change in behaviour, as the fixed tests state. However, raising QueryCanceled is not explicitly documented and not part of a strict interface, so we can probably change the exception raised without needing to wait for psycopg 4.
Close #593
=> fix: don't clobber a Python exception on COPY FROM with QueryCanceled

docs/news.rst, psycopg/psycopg/connection.py, tests/test_connection.py, tests/test_connection_async.py
Reported by David Raymond in a private message:
> With the read_only and deferrable attributes of a connection it says in the docs
"None means use the default set in the default_transaction_<attribute> configuration parameter of the server."
>
> However, while they start out as None, you cannot explicitly change those to None. When you try, it explicitly turns your value into a bool, and bool(None) is False.
>
> In the pure python version this is in connection.py, lines 233 and 252.
>
> So there's no way to reset these attributes of a connection "back to the server default". Once you set it to anything it will always be True or False, and thus explicitly start each transaction with either "BEGIN READ ONLY" or "BEGIN READ WRITE", and never again with just "BEGIN".
Bug confirmed and …
=> Fix resetting read_only and deferrable to default using None

docs/advanced/pipeline.rst, psycopg/psycopg/cursor.py, tests/test_pipeline.py, tests/test_pipeline_async.py
As described in #604, we want to discourage people to use multiple `execute()` in a pipeline to accumulate results in the same cursor.
This MR raises a warning if  `nextset()` is used after `execute()` in pipeline mode. This will become an error in 3.2 (and in a followup MR).
=> Pipeline nextset warning

tests/pool/test_pool.py, tests/pool/test_pool_async.py
We have pretty busy builders it seems.
```
FAILED tests/pool/test_pool_async.py::test_reconnect[asyncio] - AssertionError: [0.11509847640991211, 0.2041318416595459, 0.40631914138793945]
FAILED tests/pool/test_pool.py::test_reconnect - ValueError: the proxy didn't start listening in time
```
Full log: https://gist.github.com/mweinelt/046825bd23758ba799459077f117d1ba
=> Mark two more tests as timing-sensitive

docs/news.rst, psycopg/psycopg/cursor.py
The assertion on fetchall() in 'test_execute_nextset_error' now passes.
Fixes #604.
Based on #614.
=> fix!: only keep results of last execute() by a cursor in pipeline mode

docs/advanced/pipeline.rst, docs/news.rst, psycopg/psycopg/cursor.py, tests/test_pipeline.py, tests/test_pipeline_async.py
As described in #604, we want to replace the accumulation behaviour of cursors in pipeline mode with the normal clobbering behaviour.
This MR, at this moment, only replaces the `nextset()` warning introduced in #613 with an error.
The clobbering behaviour is not implemented yet. @dlax, is it something you could contribute?
=> Pipeline nextset error and clobbering behaviour

docs/advanced/cursors.rst, docs/api/cursors.rst, docs/news.rst, psycopg/psycopg/__init__.py, psycopg/psycopg/_queries.py, psycopg/psycopg/_typeinfo.py, psycopg/psycopg/raw_cursor.py, tests/fix_faker.py, tests/test_cursor.py, tests/test_cursor_async.py, tests/test_raw_cursor.py, tests/test_raw_cursor_async.py
This commit introduces support for raw queries with PostgreSQL's native placeholders ($1, $2, etc.) in psycopg3. By setting the use_raw_query attribute to True in a custom cursor class, users can enable the use of raw queries with native placeholders.
The code demonstrates how to create a custom RawQueryCursor class that sets the use_raw_query attribute to True. This custom cursor class can be set as the cursor_factory when connecting to the database, allowing users to choose between PostgreSQL's native placeholders or the standard %s placeholder in their queries. The code also demonstrates how both styles of placeholders can coexist. Test cases are included to verify the correct behavior of the new feature.
Modifications include changes to the PostgresQuery class, BaseCursor class, and …
=> Add raw query support with PostgreSQL native placeholders

docs/advanced/typing.rst, docs/api/pool.rst, docs/news_pool.rst, psycopg/psycopg/_compat.py, psycopg/psycopg/connection.py, psycopg/setup.cfg, psycopg_pool/psycopg_pool/base.py, psycopg_pool/psycopg_pool/null_pool.py, psycopg_pool/psycopg_pool/null_pool_async.py, psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py, tests/constraints.txt, tests/pool/test_null_pool.py, tests/pool/test_null_pool_async.py, tests/pool/test_pool.py, tests/pool/test_pool_async.py
This allows to have the connection returned by connection() type-annotated.
Draft to play around #558, but possibly to merge with #540 in order to specify just a connection row without subclassing.
=> make pool generic on connection type

psycopg/setup.cfg, tests/conftest.py, tests/constraints.txt, tests/pool/test_pool_async_noasyncio.py
=> chore: use AnyIO 4.0+ in tests dependencies

tests/crdb/test_connection.py, tests/crdb/test_connection_async.py, tests/test_concurrency.py, tests/test_concurrency_async.py
Went and marked all of them as timing sensitive, since they follow the same pattern.
```
____________________________ test_identify_closure _____________________________
conn_cls = <class 'psycopg.Connection'>, dsn = 'host=127.0.0.1 user=psycopg'
@pytest.mark.crdb_skip("pg_terminate_backend")
@pytest.mark.slow
def test_identify_closure(conn_cls, dsn):
def closer():
time.sleep(0.2)
conn2.execute("select pg_terminate_backend(%s)", [conn.pgconn.backend_pid])
conn = conn_cls.connect(dsn)
conn2 = conn_cls.connect(dsn)
try:
t = threading.Thread(target=closer)
t.start()
t0 = time.time()
try:
with pytest.raises(psycopg.OperationalError):
conn.execute("select pg_sleep(1.0)")
t1 = time.time()
>               assert 0.2 < t1 - t0 < 0.4
E               assert 0.2 < (1697715164.8614173 - …
```
=> Mark test_identify_closure as timing-sensitive

docs/news.rst, psycopg_c/psycopg_c/_psycopg/waiting.pyx, tests/test_concurrency.py, tests/test_concurrency_async.py
Fix #667
The sync test reproduces the issue. The async code is not affected; test added to check for regressions should we refactor the async waiting function.
@Jawshua
=> Handle gracefully EINTR on signals instead of raising InterruptedError

docs/api/dns.rst, docs/news.rst, psycopg/psycopg/_connection_base.py, psycopg/psycopg/_dns.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, psycopg/psycopg/conninfo.py, tests/_test_connection.py, tests/fix_proxy.py, tests/test_connection.py, tests/test_connection_async.py, tests/test_conninfo.py, tests/test_dns.py, tests/test_module.py, tests/test_psycopg_dbapi20.py, tools/async_to_sync.py
When using the async connection path, the libpq doesn't try connection attempts to multiple hosts. Which is kinda natural, as it doesn't enforce the timeout, so it wouldn't know when to proceed.
This MR splits a conninfo containing more than one host into a sequence of attempt, each one to be tried with the connection timeout requested, or with a finite default (set to an arbitrary 2m 10s because that's what my Ubuntu times out with).
The mechanism of splitting a conninfo into leads itself to a simpler implementation of the async DNS lookup. In particular, previously we would have looked up all the host before attempting a connection; now we look up only the host as we try to connect to.
This MR might close:
- #602
- #674 
To do:
=> Fix handling of multiple hosts

tests/fix_db.py, tests/test_connection.py, tests/test_module.py, tests/test_psycopg_dbapi20.py
These tests were previously affected by environment variables, that can be used to configure a postgresql instance.
Closes: #681
=> [maint-3.1] fix: flush PG environment variables in test_connect{,_args}

.github/workflows/tests.yml, docs/advanced/async.rst, docs/news.rst, psycopg/psycopg/waiting.py, tests/conftest.py, tests/test_gevent.py
In order to support gevent is just sufficient to avoid using the `wait_c` function; the monkeypatching mechanism can take care of it. This way `psycogreen` is not needed.
Detect that gevent has patched the `socket` module, and, if so, collaborate. Added test to prove that collaboration works as expected.
- Close #527
- Close #536
=> Fix support for gevent

docs/news.rst, psycopg/psycopg/_dns.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, psycopg/psycopg/conninfo.py, tests/test_connection.py, tests/test_connection_async.py, tests/test_conninfo.py, tests/test_dns.py, tests/test_module.py, tests/test_psycopg_dbapi20.py
The refactor introduced in 3.1.13 was taking the freedom to replace certain values with what seemed to be equivalent changes, such as replacing a missing host with an empty string
However this turned out to break the use of service file, because values taken from service files have a precedence stronger than the env vars but weaker than the connection string values (see [docs](https://www.postgresql.org/docs/current/libpq-pgservice.html)).
- #694
As a bonus, we also broke async name resolution, but that might have already been fixed
- #695
This branch cleans up some of the changes made in order to implement the handling of multiple hosts in the connection string:
- the connection string is not tampered with anymore (all the test support to consider two connection strings "equivalent" have …
=> Fix conninfo handling

.github/workflows/3rd-party-tests.yml, docs/news.rst, psycopg/psycopg/conninfo.py, tests/test_conninfo.py
Also run psycopg async in the sqlalchemy tests. This is partially connected to #703
I'm trying the pipeline at https://github.com/CaselIT/psycopg/actions/runs/7253511346
It should fail due to #703
=> Add async driver to sqlalchemy pipeline

docs/news.rst, docs/news_pool.rst, psycopg/psycopg/_compat.py, psycopg/psycopg/_pipeline.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, psycopg/psycopg/copy.py, psycopg/psycopg/crdb/connection.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py, psycopg/psycopg/pq/_debug.py, psycopg/psycopg/server_cursor.py, psycopg/psycopg/transaction.py, psycopg_pool/psycopg_pool/_compat.py, psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py, psycopg_pool/setup.cfg
The object seems available for all the supported Python version and should avoid problems with PyRight (see #708).
It is not a solution for #308 because we cannot use `Self[Row]`.
=> refactor: use typing.Self

docs/news_pool.rst, psycopg_pool/psycopg_pool/_acompat.py, psycopg_pool/psycopg_pool/base.py, psycopg_pool/psycopg_pool/null_pool.py, psycopg_pool/psycopg_pool/null_pool_async.py, psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py, tests/pool/test_pool.py, tests/pool/test_pool_async.py, tests/pool/test_pool_common.py, tests/pool/test_pool_common_async.py
Previously we failed to check when the timeout expired. Working on it, the issue of a needlessly tight loop of checks has been spotted, so we have reused the same backoff + jitter policy used in reconnection attempts (which was conveniently encapsulated into a class) to back off repeated checks too.
Close #709
=> Respect getconn timeout with failed connection checks, delay checks with backoff

docs/news.rst, psycopg/psycopg/_pipeline.py
Without it there may be a deadlock and we would be waiting to fetch a result that will never come.
Close #685.
@dlax if you have any input it would be welcome, thank you :slightly_smiling_face:
=> Fix deadline on pipeline exit

docs/news.rst, psycopg_c/psycopg_c/types/datetime.pyx, tests/types/test_datetime.py
The patch is incomplete, it only touches `IntervalLoader` implementation. Other implementations that rely on the same helper function are broken.
Should fix #719
=> fix: use long for seconds to prevent IntervalLoader from overflowing

docs/news.rst, psycopg/psycopg/pq/_pq_ctypes.py
Add a fallback to `libc.so` library name to fix loading the ctypes implementation on musl systems.  On musl, `find_library("c")` does not work (the problem has been reported to CPython in 2014, and has not been resolved yet), causing the module to fail on `assert libcname`. Instead, add a fallback to using `libc.so` and let ctypes raise an exception if such a library does not exist.
=> fix: add `libc.so` fallback for musl systems to the ctypes impl

docs/advanced/pool.rst, docs/news_pool.rst, psycopg_pool/psycopg_pool/pool_async.py, tests/pool/test_pool_async_noasyncio.py, tests/pool/test_pool_common.py, tests/pool/test_pool_common_async.py
Deprecation warnings are ignored by default and easy to miss.
Close #737.
=> Make opening an async connection pool in the constructor a runtime warning

tools/async_to_sync.py
We add a -j/--jobs option to this script and use a ProcessPoolExecutor to run conversion on files concurrently. The option can be used with no value to make use of all available processors.
=> feat(tools): possibly run async_to_sync.py concurrently

docs/lib/libpq_docs.py
If we now set libpq_docs_version to 'devel', the pq Sphinx role will use the master branch when looking libpq.sgml and the 'devel' URL component when linking to libpq online documentation.
* * *
That's something I find useful in order to check if the docs built for #754 are correct by locally tweaking:
```diff
diff --git a/docs/conf.py b/docs/conf.py
index cafcb5e6..db3a017e 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -106,7 +106,7 @@ intersphinx_mapping = {
autodoc_member_order = "bysource"
-libpq_docs_version = "14"
+libpq_docs_version = "devel"
ticket_url = "https://github.com/psycopg/psycopg/issues/%s"
diff --git a/docs/lib/libpq_docs.py b/docs/lib/libpq_docs.py
index 2868916f..053fd693 100644
--- a/docs/lib/libpq_docs.py
+++ b/docs/lib/libpq_docs.py
@@ -183,6 +183,6 @@ def …
```
=> docs: let the 'pq' role possibly link to "devel" PostgreSQL docs

psycopg/psycopg/pq/_pq_ctypes.py, psycopg_c/psycopg_c/pq/pgconn.pyx
I can't find how my editor is set up, but it doesn't complain on this file, and yet calling mypy on this file only will find several error.
Having seen @dlax adding `type: ignore[no-any-return]` comments makes me want to fix this.
=> More compact guards of libpq optional functions

docs/news_pool.rst, psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py
The case has been reported in #784. While not easy to reproduce, it seems that it might be caused by the pool being closed while a worker is still trying to create a connection, which will be put in the _pool state after supposedly no other operation should have been performed.
Stop the workers and then empty the pool only after they have stopped to run.
Also refactor the cleanup of the pool and waiting queue, moving them to close(). There is no reason why a method called "stop workers" should empty them, and there is no other code path that use such feature.
Close #784.
@adriangb could you please try if this changeset fixes your problem?
=> fix(pool): make sure there are no connection in the pool after close()

docs/advanced/pipeline.rst, docs/advanced/prepare.rst, docs/api/connections.rst, docs/api/module.rst, docs/api/objects.rst, docs/news.rst, psycopg/psycopg/__init__.py, psycopg/psycopg/_capabilities.py, psycopg/psycopg/_pipeline.py, psycopg/psycopg/pq/__init__.py, psycopg/psycopg/pq/_pq_ctypes.py, psycopg/psycopg/pq/misc.py, psycopg_c/psycopg_c/pq/pgconn.pyx, tests/fix_db.py, tests/pq/test_misc.py, tests/pq/test_pq.py, tests/test_capabilities.py, tests/test_generators.py, tools/update_oids.py
The object, exposed as `psycopg.capabilities`, exposes `has_STUFF()` methods to verify if a certain feature is supported.
If `check=True` is specified, raise an exception instead of returning False, with a finely crafted message such as:
> the feature 'Connection.pipeline()' is not available: you are using a psycopg[c] libpq wrapper built with libpq version 9.5.3; the feature requires libpq version at least 14.0
>
> the feature 'Connection.pipeline()' is not available: the client libpq version (imported from system libraries) is 13.4; the feature requires libpq version at least 14.0
>
> the feature 'Connection.pipeline()' is not available: the client libpq version (imported from psycopg[binary] version 3.2.0) is 13.4; the feature requires libpq version at least 14.0
helping to diagnose …
=> Add capabilities objects

docs/api/connections.rst, psycopg/psycopg/_connection_base.py, psycopg/psycopg/_conninfo_attempts.py, psycopg/psycopg/_conninfo_attempts_async.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py
I have cleaned up both `cancel()` and `cancel_safe()`. Both the methods now consistently warn and swallow exceptions on error, but only in the outermost shell; inner methods are more purely mechanism.
Close #778. In preparation for #779. Can make use of #782.
=> Review cancel methods implementations

psycopg_c/psycopg_c/_psycopg/waiting.pyx
This resolves the following warning when building the extension module:
$ python psycopg_c/setup.py build_ext -i
[...]
building 'psycopg_c._psycopg' extension
x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/denis/.local/pgsql/include -I/home/denis/src/psycopg3/.venv/include -I/usr/include/python3.11 -c psycopg_c/_psycopg.c -o build/temp.linux-x86_64-cpython-311/psycopg_c/_psycopg.o
psycopg_c/_psycopg.c: In function ‘wait_c_impl’:
psycopg_c/_psycopg.c:1649:1: warning: label ‘error’ defined but not used [-Wunused-label]
1649 |
| ^
=> fix(c): fix the goto label in the HAVE_POLL branch of wait_c_impl()

docs/news.rst, psycopg/psycopg/conninfo.py, tests/test_conninfo.py
The [`connect_timeout`](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-CONNECT-TIMEOUT) parameter is specified as integer.
It seems that certain libpq versions handle correctly a floating point connect timeout:
```
$ psql connect_timeout=5.0
psql (11.22 (Debian 11.22-0+deb10u2), server 16.2)
WARNING: psql major version 11, server major version 16.
Some psql features might not work.
Type "help" for help.
```
others don't
```
$ psql --version
psql (PostgreSQL) 16.2 (Ubuntu 16.2-1.pgdg22.04+1)
$ psql "connect_timeout=5.0"
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: invalid integer value "5.0" for connection option "connect_timeout"
```
Psycopg doesn't, but mostly by accident, and in the recent version where the connection …
=> fix: fix handling of floating point values for connect_timeout

psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py
With the previous change to avoid finding open connections in the pool (#784), stopping the worker was moved into the critical section. This can create a deadlock in case a worker is in the process of obtaining a new connection, because putting it to the pool requires the lock. The deadlock only last for the default 5s timeout passed to _stop_workers().
Solve the problem by guarding _add_to_pool() to avoid it to try to add the connection if the pool is closed.
However, refactor the pool closing sequence too and close the workers and other resources that now out of the state outside the critical section to keep the operation running under lock to a minimum.
=> Avoid possible deadlock (until timeout) on pool closing

docs/news.rst, psycopg/psycopg/_copy.py, psycopg/psycopg/_copy_async.py, psycopg/psycopg/_copy_base.py, psycopg/psycopg/generators.py, tests/scripts/copytest.py, tests/test_copy.py, tests/test_copy_async.py
Fixes #745 
I kept the flush code the same as `copy_end`, but think it may be better to break if `f != 1` instead of `f == 0` in both places to account for errors, which return -1 ([Postgres docs](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQFLUSH)).
=> Improve performance of copy

docs/news_pool.rst, psycopg_pool/psycopg_pool/pool.py, psycopg_pool/psycopg_pool/pool_async.py
From #790:
> The current implementation of `psycopg_pool.pool.ConnectionPool.check_connection` uses the `SELECT 1` statement to check if a connection is valid.
> 
> However this goes through the PostgreSQL query planner which means we can make this process a little bit faster by sending an empty query instead.
> 
> This can be done by replacing `conn.execute("SELECT 1")` with `conn.execute("--ping")`
> 
> References:
> - https://github.com/rails/rails/pull/42368
> - [jackc/pgx ping implementation (Go)](https://github.com/jackc/pgx/blob/a3d9120636fc263debce595f3ba05bcd9f4ee809/pgconn/pgconn.go#L1815-L1817)
> - https://github.com/sqlalchemy/sqlalchemy/issues/8491
=> Replace SELECT 1 with an empty query

docs/news.rst, psycopg/psycopg/connection.py
We started using the extended protocol in e5079184 to fix #350, but, probably to keep symmetry, we also changed the behaviour out of the pipeline.
This turns out to be a problem for people connecting to the PgBouncer admin console. They can use the `ClientCursor`, which tries to use the simple protocol as much as it can, but they currently have to use autocommit. With this changeset autocommit shouldn't be needed anymore. See #808.
=> Use simple query protocol to execute BEGIN/COMMIT out of pipeline mode

.github/dependabot.yml, .github/workflows/3rd-party-tests.yml, .github/workflows/docs.yml, .github/workflows/packages-bin.yml, .github/workflows/packages-pool.yml, .github/workflows/packages-src.yml
Updates the actions which could be done with little to minimal changes.. Includes a monthly dependabot check for actions now.
This is motivated by recent updates to the Node 16 availability for runners: https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/
Changelogs for review:
- https://github.com/actions/cache/releases/tag/v4.0.0
- https://github.com/actions/upload-artifact/releases/tag/v4.0.0
- Required the most changes due to how uploads work now.  Each upload needs a distinct name now, so each build produces a new artifact
- See also https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
- If desired, I can attempt to merge them all at the end
- https://github.com/docker/setup-qemu-action/releases/tag/v3.0 …
=> chore: Updates action versions and add dependabot to check monthly for updates

docs/news.rst, psycopg_c/psycopg_c/_psycopg/copy.pyx
We missed to reset the number of chars to escape at every field. As a consequence, we end up resizing and scanning all the fields after the first one requiring an escape and allocating a bit more memory than needed.
=> Fix count of chars to escape in textual copy dump

docs/api/cursors.rst, docs/api/objects.rst, docs/news.rst, psycopg/psycopg/_capabilities.py, psycopg/psycopg/_cursor_base.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py, psycopg/psycopg/rows.py, tests/test_capabilities.py, tests/test_cursor_common.py, tests/test_cursor_common_async.py
=> add a 'size' parameter to Cursor.stream()

psycopg/psycopg/_connection_base.py, psycopg/psycopg/_cursor_base.py, tests/_test_copy.py, tests/_test_transaction.py, tests/crdb/test_copy.py, tests/crdb/test_copy_async.py, tests/crdb/test_cursor.py, tests/crdb/test_cursor_async.py, tests/test_connection.py, tests/test_connection_async.py, tests/test_copy.py, tests/test_copy_async.py, tests/test_cursor_common.py, tests/test_cursor_common_async.py, tests/test_cursor_server.py, tests/test_cursor_server_async.py, tests/test_transaction.py, tests/test_transaction_async.py
Unused in the codebase, and not documented. Only used in the test suite.
Because they haven't been documented I think we can drop them safely.
=> chore: drop pq enums aliases on connection and cursor

psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/test_notify.py, tests/test_notify_async.py
With the previous implementation, it was possible to sneak an execute() while the generator is consumed. This gives the false impression that it's possible to use the connection while listening (see #756), which is false for reason better explored in #757.
Therefore, lock the connection while listening to notifications. If someone wants to mix commands with listening on the same connection, they should do it collaboratively with an adequately short notifies() timeout.
=> fix: lock the connection during a 'notifies()' call

docs/advanced/prepare.rst, docs/api/objects.rst, psycopg/psycopg/_capabilities.py, psycopg/psycopg/_connection_base.py, tests/test_capabilities.py
This is a capability we need internally. `has_pgbouncer_prepared()` is pretty much just an alias of it, more outwards-facing. I wonder if we want to keep them both.
=> feat(capabilities): add has_send_close_prepared()

.github/workflows/packages-bin.yml, docs/news.rst, tools/build/build_libpq.sh, tools/build/wheel_linux_before_all.sh
This is a pretty long jump, previously used version was 1.1.1, which is now unsupported.
In the past, bundling openssl 0.9.8 was causing random segfaults when the python-bundled openssl was used too (e.g. requesting an https url via urllib). See https://github.com/psycopg/psycopg2/issues/543. A lot of time has passed, and hopefully the case shouldn't present again. Unfortunately it's not easy to test (I was never able to reproduce the bug above).
=> Update openssl to 3.3.1

psycopg/psycopg/types/multirange.py, psycopg/psycopg/types/range.py, tests/types/test_multirange.py, tests/types/test_range.py
If a range has no type information (e.g. is empty and it is a base class, not a specific range subtype), `upgrade()` would have returned a text dumper. This would have resulted in protocol violation, such as requesting unhealthy amount of memory to the backend... and it was tested too!
Restoring sanity has a drawback. If we have an array of ranges, none of which has type information, we now fail binary dumping. Previously this worked, provided that a cast `::int8range[]` was provided, but I think with an extreme stretch of the protocol: we were producing binary arrays containing text representation of the ranges.
I don't think the latter is quite valid. So I have a preference for dropping the feature in exchange of not violating the protocol. We trade a better dumping of the basic type …
=> Avoid to dump [multi]range as text when binary is requested

psycopg_c/build_backend/cython_backend.py, psycopg_c/pyproject.toml
It is in the stdlib. No need to have wheel building require downloading yet another build dependency.
=> build: avoid installing tomli on recent python

docs/news.rst, psycopg/psycopg/abc.py, psycopg/psycopg/pq/abc.py, psycopg/psycopg/rows.py, psycopg_pool/psycopg_pool/abc.py
I have looked for TypeAlias defined as strings by looking for `TypeAlias = "` in the codebase.
I have fixed the occurrences that causes #860, but left the internal ones as they are. String TypeAlias not fixed at the moment are the following ones. IMO they are not worth fixing.
```
psycopg_pool/psycopg_pool/_acompat.py
33:AWorker: TypeAlias = "asyncio.Task[None]"
psycopg/psycopg/errors.py
34:ErrorInfo: TypeAlias = "PGresult | dict[int, bytes | None] | None"
psycopg/psycopg/_py_transformer.py
32:DumperCache: TypeAlias = "dict[DumperKey, abc.Dumper]"
33:OidDumperCache: TypeAlias = "dict[int, abc.Dumper]"
34:LoaderCache: TypeAlias = "dict[int, abc.Loader]"
psycopg/psycopg/_preparing.py
22:Key: TypeAlias = "tuple[bytes, tuple[int, ...]]"
psycopg/psycopg/types/enum.py
25:EnumDumpMap: TypeAlias …
```
=> Drop string TypeAlias

docs/api/pq.rst, docs/conf.py, docs/lib/libpq_docs.py
We bump `libpq_docs_version = "17"` in docs configuration (first commit), as the `REL_17_STABLE` branch is now available in PostgreSQL git repository. And then document features of libpq 17: `PGCancelConn` and `change_password()`.
#534
=> document libpq 17 features

docs/basic/usage.rst
=> docs: fix typo in Basic module usage

docs/advanced/pool.rst
The FastAPI `@app.on_event("startup")` and  `@app.on_event("shutdown")` are deprecated. This PR simply replaces their usage in the AsyncConnectionPool section with the now recommened Lifespan.
=> docs: replace fastapi events with lifespan

psycopg/psycopg/pq/misc.py
Might fix the problem mentioned in #912 about finding the dll locally.
=> fix(windows): resolve absolute path to libpq

tests/test_notify.py, tests/test_notify_async.py
When the machine is under load, any tests relying on a timeout or a sleep is subject to fail. Let's mark some of them as 'timing'.
I followed the recommandation in [a comment on a similar issue](https://github.com/psycopg/psycopg/issues/692#issuecomment-1838118714).
Context: these failing tests have been discovered when automatically testing a geos update on nixpkgs. The process rebuilds all geos dependencies, and put my laptop under a quite high load. That being said, I reproduce sometimes even when limiting the number of workers `nixpkgs-review` is able to use.
Thanks for the awesome lib!
=> test: mark more tests as 'timing'

docs/basic/from_pg2.rst
In the code example demonstrating that `IS %s` isn't possible:  The `IS NOT DISTINCT FROM` operator is used
However in the accompanying text reads:
*"instead is to use the `IS DISTINCT FROM`"*
I've read this a few times and I think the text should read:
*"instead is to use the `IS NOT DISTINCT FROM`"*
Thanks for the work maintaining this btw, psycopg is great :)
=> docs: ensure operator in text and code example matches

tests/types/test_numpy.py
Addresses the issue #945 .
Added branching for type sizes depending on system architecture.
=> Fix `test_classes_identities` for 32 and 64 architectures

tools/build/build_macos_arm64.sh
```diff
- python_versions="3.8.19 3.9.19 3.10.14 3.11.9 3.12.5 3.13.0rc1"
+ python_versions="3.8.19 3.9.19 3.10.14 3.11.9 3.12.5 3.13.0"
```
=> build_macos_arm64.sh: Upgrade to Python 3.13 production release

README.rst
- Add macOS and Windows install instructions for `libpq`
- This is also required e.g. to run cross-platform zipapps generated with https://github.com/linkedin/shiv that include Psycopg as a dependency, because I think that using any C code (e.g. `psycopg-binary`) is not a viable option in this case
If this is merged, could https://pypi.org/project/psycopg/#description be updated to include this README section? I would've helped me a lot because a zipapp that I generated with `shiv` wasn't working on another platform and I didn't know why.
=> Extend `libpq` install instructions for cross-platform use

.github/workflows/packages-bin.yml, .github/workflows/tests.yml, .gitignore, tools/build/pg_config_vcpkg_stub/pg_config_vcpkg_stub/__init__.py, tools/build/pg_config_vcpkg_stub/pyproject.toml, tools/build/wheel_win32_before_build.bat
ref: https://github.com/psycopg/psycopg/issues/916
It build wheel as expected:
https://github.com/trim21/psycopg/actions/runs/12343652281
=> ci: use vcpkg to install libpq on windows

.github/workflows/3rd-party-tests.yml, .github/workflows/packages-bin.yml, .github/workflows/tests.yml, docs/basic/install.rst, docs/news.rst, docs/release.rst, psycopg/psycopg/_acompat.py, psycopg/psycopg/abc.py, psycopg/psycopg/pq/abc.py, psycopg/psycopg/rows.py, psycopg/pyproject.toml, psycopg_c/pyproject.toml, psycopg_pool/psycopg_pool/_acompat.py, psycopg_pool/psycopg_pool/abc.py, psycopg_pool/pyproject.toml, tests/README.rst, tests/acompat.py, tests/constraints.txt, tools/build/build_macos_arm64.sh, tools/bump_version.py
Partially addresses the issue #976 .
Should go after the PR #974 .
=> Drop Py3.8 dependencies from `pyproject.toml`s and CI/CD workflows

docs/news.rst, psycopg/psycopg/_connection_base.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/test_notify.py, tests/test_notify_async.py
This allows to stop periodically the generator to run some queries (for example to LISTEN/UNLISTEN certain channels) and start the generator again without fearing to lose notification in the window.
We add a deque to the connection, that gets populated by the notifies handler, and is consumed by `notifies()` before listening for new notifications received.
Cloes #962.
=> Don't lose notifications while notifies() is not running

.github/workflows/lint.yml, .pre-commit-config.yaml, README.rst, docs/lib/libpq_docs.py, docs/lib/pg3_docs.py, docs/lib/sql_role.py, psycopg/psycopg/_cmodule.py, psycopg/psycopg/_connection_base.py, psycopg/psycopg/_copy_base.py, psycopg/psycopg/_cursor_base.py, psycopg/psycopg/pq/_pq_ctypes.py, psycopg/psycopg/pq/pq_ctypes.py, psycopg/pyproject.toml, psycopg_c/build_backend/psycopg_build_ext.py, pyproject.toml, tests/scripts/pipeline-demo.py, tests/test_adapt.py, tests/types/test_array.py, tools/update_backer.py
This MR adds pre-commit hooks to run black, codespell, flake8, mypy. This allows contributors to find issues before submitting changes that will be rejected by the lint step.
The linters are executed in the dev virtualenv, instead of in a separate virualenv as pre-commit does. In my experience, a separate environment creates problems and makes the behaviour more obscure.
Note that it's not easy to add async-to-sync to the pre-commit hook in a generic way because it depends either on a specific system python version installed or on docker/podman.
Note that running:
- `mypy` (uses the files in `pyproject.toml`)
- `mypy .` (runs on every file)
- `mypy FILE1.py` (typically run by an editor)
- `mypy FILE1.py FILE2.py` (typically run by `pre-commit run -a`)
seem to yield different result. The …
=> Add pre-commit hooks

psycopg/psycopg/abc.py
May fix the issue #921 .
Won't work in Py3.8, follows the #976 .
UPD: Should go after #982 .
=> Fix `Dumper.get_key` method return type

docs/news.rst, psycopg/psycopg/generators.py, psycopg/psycopg/pq/_debug.py, psycopg_c/psycopg_c/_psycopg/generators.pyx, tests/test_connection.py, tests/test_connection_async.py
Avoid that an exception caused by a disconnection clobbers a server error already received as result. This happens when the server returns an error and immediately closes the connection, such as when hitting an idle-in-transaction timeout.
Close #988.
=> Fix clobbered error on disconnect

psycopg/psycopg/_connection_base.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py
Just keep the queue in the state and special-case its handling in the connection handling instead of using the handler like a standard one. Set the queue to None to signify that we are in the handler.
This way we don't need the awkward weak-self + class method to avoid a reference loop and to dereference the connection weak reference another time, as we just did in `_notify_handler()`. Setting the queue to None also feels cleaner than adding/removing the handler.
Relates to #975.
=> refactor: don't keep the notifiers backlog handler in the connection state

.github/workflows/packages-bin.yml, tools/build/build_libpq.sh, tools/build/wheel_macos_before_all.sh
Build the libpq from source, instead of using Homebrew libraries, on macOS.
This avoids problems with `MACOSX_DEPLOYMENT_TARGET` drifting in builders (see https://github.com/psycopg/psycopg/issues/858).
Largely contributed by @bwoodsend in https://github.com/psycopg/psycopg2/pull/1755. Thank you very much!
=> Build libpq on macOS

psycopg/psycopg/pq/misc.py
If we can't find `libpq.dll` on windows, `libname` will be `None`, and psycopg will raise a very unreadable error about `None` missing `__fspath__` instead of expected `ImportError("libpq library not found")`
see here, for example: https://github.com/psycopg/psycopg/actions/runs/13475336675/job/37653819602?pr=1012
=> fix: win32 libpq missing error message should be more clear

psycopg/psycopg/pq/misc.py
Hi! I am working on mypy in https://github.com/python/mypy/pull/18797
And I've noticed a small thing in your code. Ideally, `SomeEnum.Item.name` should be inferenced as `Literal[NAME_ONE, NAME_TWO, ...]`
But, since you later modify `status` (which is the name of a enum item), it should be explicitly annotated as `str`, not `Literal`.
=> Fix how `status` is inferenced in `connection_summary`

docs/news.rst
I seemed like these section headers were supposed to be psycopg not python in the webpage about releases.
=> Rename some news.rst section headers from python to psycopg

psycopg/psycopg/generators.py, psycopg/psycopg/pq/misc.py, psycopg_c/psycopg_c/_psycopg/generators.pyx
Adding persistent debug logging at connection time.
```
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)s %(message)s')
>>> logging.getLogger("psycopg").setLevel(logging.DEBUG)
>>> import psycopg
>>> conn = psycopg.connect("host=localhost")
2025-04-29 16:18:58,808 DEBUG connection started: <psycopg.pq.pq_ctypes.PGconn [STARTED] at 0x775278568810>
2025-04-29 16:18:58,808 DEBUG connection polled: <psycopg.pq.pq_ctypes.PGconn [AWAITING_RESPONSE] at 0x775278568810>
2025-04-29 16:18:58,808 DEBUG connection polled: <psycopg.pq.pq_ctypes.PGconn [NEEDED] at 0x775278568810>
2025-04-29 16:18:58,810 DEBUG connection polled: <psycopg.pq.pq_ctypes.PGconn [NEEDED] at 0x775278568810>
2025-04-29 16:18:58,811 DEBUG connection polled: …
```
=> Add connection log info

docs/api/cursors.rst, psycopg/psycopg/_cursor_base.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py
The original definition can be confusing (at least it was for me) because if you run several commands separated by `;` in a single `cursor.execute`, the `cursor.statusmessage` attribute retains the tag from the first command. For example:
```py
query = """
CREATE TABLE table1 (val INT, val2 INT);
INSERT INTO table1 (val, val2) VALUES (10, 20);
"""
cursor.execute(query=query)
print("Execute 1:", cursor.statusmessage)
cursor.execute(query="DROP TABLE table1;")
print("Execute 2:", cursor.statusmessage)
```
This will result in:
```
Execute 1: CREATE TABLE
Execute 2: DROP TABLE
```
But according to the original description, it should be:
```
Execute 1: INSERT
Execute 2: DROP TABLE
```
=> Clarify docstring for BaseCursor.statusmessage

.github/workflows/3rd-party-tests.yml, .github/workflows/packages-bin.yml, .github/workflows/packages-pool.yml, .github/workflows/packages-src.yml, .github/workflows/tests.yml, docs/basic/install.rst, docs/news.rst, psycopg/pyproject.toml, psycopg_c/pyproject.toml, psycopg_pool/pyproject.toml, tests/README.rst, tests/constraints.txt, tests/fix_faker.py, tests/scripts/bench-411.py
Remove usage of Python 3.9 in the following directories:
- .github/workflows
- docs
- psycopg
- psycopg_c
- psycopg_pool
- tests
See #1056
=> Drop support for Python 3.9

psycopg/psycopg/_cursor_base.py, tests/test_cursor_common.py, tests/test_cursor_common_async.py
Print the last command status with the error. For example:
the last operation didn't produce records (command status: NOTIFY)
or, if the result doesn't even have a command status:
the last operation didn't produce records (result status: EMPTY_QUERY)
Related to #1062.
=> Improve error message trying to fetch from a no recordset result

docs/advanced/typing.rst, docs/api/cursors.rst, docs/news.rst, psycopg/psycopg/_server_cursor.py, psycopg/psycopg/_server_cursor_async.py, psycopg/psycopg/_server_cursor_base.py, psycopg/psycopg/cursor.py, psycopg/psycopg/cursor_async.py, tests/test_cursor_common.py, tests/test_cursor_common_async.py, tests/test_cursor_server.py, tests/test_cursor_server_async.py, tests/test_typing.py, tools/async_to_sync.py
This MR transforms the cursor from an iterable (supporting `iter()`) to an iterator (supporting `iter()` and `next()`).
`next(cursor)` behaves like `cursor.fetchone()`, but its result is `Row`, not `Row | None`. That's because, if there is no row to fetch, it will raise `StopIteration`.
This makes simpler to write strictly typed code using the result when there is a 100% guarantee that a query will return a record (or will raise an exception), for example when fetching `count(*)`, which always returns a result even if the counted records are 0. The type checker is not aware of that, therefore you need to guard for None with an `if`, or an `assert`, or you need to do something horrible like `(rec,) = cur.fetchall()` in order to convince Mypy that `rec` will never be none.
=> Add support for `next(cursor)`

psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/test_connection.py, tests/test_connection_async.py
This PR fixes #1069.
It updates the connection failure logic to preserve all error messages for the various attempts. Previously, only the message from the final attempt was shown the user, which created confusing situations as described in #1069.
Below is an example of the new message format:
```
psycopg.OperationalError: connection failed: connection to server at "1.2.3.4", port 5432 failed: FATAL:  unable to accept connection, access denied
DETAIL:  Session Id: ghijklmnp4yquucuzkab7hhka
Multiple connection attempts failed. All failures were:
- host: 'redacted.for.github', port: None, hostaddr: '2200:1f18:1f72:a404:61e8:e38a:6be2:fake': connection failed: connection to server at "2200:1f18:1f72:a404:61e8:e38a:6be2:fake", port 5432 failed: FATAL:  unable to accept connection, access …
```
=> fix: show all messages associated with connection failures

docs/news.rst, psycopg_c/psycopg_c/types/numutils.c, tools/build/ci_install_libpq.sh
The first commit in this MR should address the immediate failure to build the C module with v18 includes. Running the tests in the grid to try with more versions.
We should add CI support to test building from postgres libpq master.
=> Add support for libpq v18

docs/news.rst, psycopg_c/psycopg_c/_psycopg/generators.pyx, tests/test_concurrency_async.py
Repro kindly provided by @zzzeek and @coby-astsec in MagicStack/asyncpg#1265 and converted for our test suite. Thank you very much!
Fix #1005.
=> Avoid a TypeError shadowing CancelledError on task cancellation

docs/basic/from_pg2.rst
`.format()` was incorrectly placed out of `.SQL()`.
=> Fixing a small typo

psycopg_c/psycopg_c/types/numeric.pyx
@dvarrazzo There is no testcase for this, as I dont know how to test this (it is a cdef function, the value gets immediately corrected by the only reachable outer dump function).
=> fix buffer sizing for Int2BinaryDumper in c version

docs/advanced/async.rst, docs/news.rst, psycopg/psycopg/_connection_base.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/test_notify.py, tests/test_notify_async.py
Opening this MR to look into this way to fix the issue is reasonable and if it doesn't cause problems somewhere else.
If someone is listening to notifications by using an handler, the notifies backlog would fill without ever being emptied: see #1091.
This change has the risk of breaking something if someone is relying on notifies being received both via callback and via generator, but I don't know how to satisfy it without creating a leak to users who don't use the generator.
The MR changes the tests because `test_notify_query_notify` doesn't pass anymore. The test is now split in two testing notifies and generator separately.
=> Collect notifies only if no handler is registered

.github/workflows/packages-bin.yml, docs/news.rst, psycopg/psycopg/_conninfo_utils.py, psycopg/psycopg/connection.py, psycopg/psycopg/connection_async.py, tests/pq/test_pq.py, tests/test_connection.py, tests/test_connection_async.py, tools/ci/build_libpq.sh
The MR builds on top of #1137, but it targets the master branch.
Tentatively scheduled for release in 3.3.
Fix #1136
=> Set gssencmode default to disable in binary package builds
